# Generated by Django 3.0.6 on 2020-06-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200607_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_by',
            field=models.CharField(default='user', max_length=64),
        ),
    ]
