# Generated by Django 3.0.6 on 2020-06-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200607_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='created_by',
            field=models.CharField(default='user_t', max_length=64),
        ),
    ]
