# Generated by Django 3.0.6 on 2020-06-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='token',
            field=models.CharField(default='fuck', max_length=120),
        ),
    ]
